name: Publish
# When a new Github Release is created, publish to NPM
on:
  release:
    types: [published]
  push:
    branches:
      - postrelease_test

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Package
        uses: actions/checkout@v2
        with:
          ref: v2.24.0
      - name: Setup Node environment
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: NPM Install
        run: npm install
      - name: NPM run build
        run: npm run build
      - name: Get npm tag name if needed
        id: npm_tag
        run: |
          pre_release_name=2.24.0
          echo "Pre release name:" $pre_release_name
          echo ::set-output name=npm_tag::$pre_release_name
      - name: Wait for 60 seconds
        run: sleep 60s
        shell: bash
  deploy_chime_prod_demo:
    needs: publish
    name: Prod - Chime Client - Deploy the Serverless Meeting Demos
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: text
      NAME: ChimeProd
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.PROD_AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Checkout Package
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.npm_version.outputs.npm_version }}
      - name: Get current published version
        id: npm_version
        run: |
          current_version=$(.github/script/get-current-version)
          echo "Current released version:" $current_version
          echo ::set-output name=npm_version::$current_version
      - name: Install SDK and verify npm version
        run: |
          cd demos/browser
          npm uninstall amazon-chime-sdk-js
          npm install amazon-chime-sdk-js@${{ steps.npm_version.outputs.npm_version }}
      - name: Verify npm version
        run: |
          demo_current_version=2.24.0
          echo "Current demo version:" $demo_current_version
          if demo_current_version != "^#${{ steps.npm_version.outputs.npm_version }}"
          then
            echo "npm version is not the same as the current version"
          else
            npm run build
            npm run build --app=meetingReadinessChecker
            ../../script/github-action-awscli-installation
            ../../script/postrelease
          fi
      #- name: Install SAM CLI
       # run: script/github-action-awscli-installation
      #- name: Run Deployment Script
        #run: script/postrelease
  deploy_chime_prod_demo_iad:
    needs: publish
    name: Prod - ChimeSDKMeetings Client - Deploy the Serverless Meeting Demos
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: text
      NAME: ChimeSDKMeetingsProdIAD
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.PROD_AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Checkout Package
        uses: actions/checkout@v2
        with:
          ref: v${{ needs.publish.outputs.npm_version }}
      - name: Get current published version
        id: npm_version
        run: |
          current_version=$(.github/script/get-current-version)
          echo "Current released version:" $current_version
          echo ::set-output name=npm_version::$current_version
      - name: Install SDK and verify npm version
        run: |
          cd demos/browser
          npm uninstall amazon-chime-sdk-js
          npm install amazon-chime-sdk-js@${{ steps.npm_version.outputs.npm_version }}
      - name: Verify npm version
        run: |
          demo_current_version=2.24.0
          echo "Current demo version:" $demo_current_version
          if demo_current_version != "^#${{ steps.npm_version.outputs.npm_version }}"
          then
            echo "npm version is not the same as the current version"
          else
            npm run build
            npm run build --app=meetingReadinessChecker
            ../../script/github-action-awscli-installation
            ../../script/postrelease
          fi