name: Publish
# When a new Github Release is created, publish to NPM
on:
  release:
    types: [published]
  push:
    branches:
      - postrelease_test

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Package
        uses: actions/checkout@v2
        with:
          ref: v2.24.0
      - name: Setup Node environment
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: NPM Install
        run: npm install
      - name: NPM run build
        run: npm run build
  deploy_chime_prod_demo:
    needs: publish
    name: Prod - Chime and ChimeSDKMeetings Client - Deploy the Serverless Meeting Demos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [ ChimeProd, ChimeSDKMeetingsProdIAD, ChimeSDKMeetingsProdPDX, ChimeSDKMeetingsProdFRA, ChimeSDKMeetingsProdSIN ]
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: text
      NAME: ${{ matrix.name }}
    steps:
      - name: Verify the npm version is available
        id: npm_version
        run: |
          tag_name=v2.4.0
          current_version=${tag_name:1}
          max_wait_time=300
          wait_time=0
          sleep_time=60
          while :
          do
            if [[ $wait_time -ge $max_wait_time ]]
            then
              echo "Version is not published to npm:" $current_version
              exit 1
            fi
            echo $wait_time
            npm_version=$(npm view amazon-chime-sdk-js@${current_version} version)
            if [[ *$npm_version* = *$current_version* ]]
            then
              echo "Version is published to npm:" $current_version
              echo ::set-output name=npm_version::$current_version
              break
            fi

            sleep $sleep_time
            wait_time=$((wait_time+sleep_time))
            done
        shell: bash
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.PROD_AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Checkout Package
        uses: actions/checkout@v2
        with:
          ref: v2.24.0
      - name: Install SDK and verify npm version
        run: |
          cd demos/browser
          npm uninstall amazon-chime-sdk-js
          npm install amazon-chime-sdk-js@${{ steps.npm_version.outputs.npm_version }}
      - name: Verify npm version
        run: |
          demo_current_version=^2.25.0
          echo "Current demo version:" $demo_current_version
          if [[ *$demo_current_version* != "^#${{ steps.npm_version.outputs.npm_version }}" ]];
          then
            echo "npm version is not the same as the current version"
            exit 1
          else
            npm run build --app=meetingReadinessChecker
            script/github-action-awscli-installation
            script/deploy-canary-demo
          fi