name: Publish
# When a new Github Release is created, publish to NPM
on:
  release:
    types: [published]
  push:
    branches:
      - postrelease_test

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Package
        uses: actions/checkout@v2
      - name: Setup Node environment
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: NPM Install
        run: npm install
      - name: Wait for 60 seconds
        run: sleep 60s
        shell: bash
  deploy_chime_prod_demo:
    needs: publish
    name: Prod - Chime Client - Deploy the Serverless Meeting Demos
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: text
      NAME: ChimeProd
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.PROD_AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Get current npm version
        run: |
          current_version=$(.github/script/get-current-version)
          echo "Released version:" $current_version
          echo ::set-output name=npm_tag::$current_version
      - name: Checkout Package
        uses: actions/checkout@v2
        with:
          ref: refs/tags/$current_version
      - name: Install the Chime SDK
        run: |
          cd demos/browser
          npm uninstall amazon-chime-sdk-js
          npm install amazon-chime-sdk-js@$current_version
      - name: Install SAM CLI
        run: script/github-action-awscli-installation
      - name: Run Deployment Script
        run: script/postrelease
  deploy_chime_prod_demo_iad:
    needs: publish
    name: Prod - ChimeSDKMeetings Client - Deploy the Serverless Meeting Demos
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: text
      NAME: ChimeSDKMeetingsProdIAD
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.PROD_AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Get current npm version
        run: |
          current_version=$(.github/script/get-current-version)
          echo "Released version:" $current_version
          echo ::set-output name=npm_tag::$current_version
      - name: Checkout Package
        uses: actions/checkout@v2
        with:
          ref: refs/tags/$current_version
      - name: Install the Chime SDK
        run: |
          cd demos/browser
          npm uninstall amazon-chime-sdk-js
          npm install amazon-chime-sdk-js@$current_version
      - name: Install SAM CLI
        run: script/github-action-awscli-installation
      - name: Run Deployment Script
        run: script/postrelease